/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "ink-on-dark": "#141414",
        "on-tertiary-container": "#848484",
        "primary-container": "#1b1b1b",
        "surface": "#f9f9f9",
        "error": "#ba1a1a",
        "surface-variant": "#e2e2e2",
        "tertiary": "#000000",
        "status-urgent-fg": "#C17F6B",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dadada",
        "on-primary-container": "#848484",
        "on-surface-variant": "#4c4546",
        "inverse-on-surface": "#f1f1f1",
        "accent-sage": "#E0EEDD",
        "background": "#f9f9f9",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-primary": "#ffffff",
        "inverse-surface": "#303030",
        "tertiary-container": "#1b1b1b",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#474747",
        "secondary-container": "#eee2c2",
        "on-secondary-container": "#6d644b",
        "bg-accent": "#F7EACA",
        "status-upcoming-fg": "#646A6A",
        "on-secondary-fixed-variant": "#4e462f",
        "on-surface": "#1b1b1b",
        "surface-bright": "#f9f9f9",
        "muted-divider": "#D9D9D9",
        "secondary-fixed": "#eee2c2",
        "accent-mint": "#DFEDED",
        "primary-fixed": "#e2e2e2",
        "secondary": "#665e45",
        "on-secondary-fixed": "#211b08",
        "on-primary-fixed": "#1b1b1b",
        "outline": "#7e7576",
        "on-background": "#1b1b1b",
        "status-attention-fg": "#6F695A",
        "primary": "#000000",
        "surface-container": "#eeeeee",
        "on-tertiary-fixed-variant": "#474747",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "status-urgent-bg": "#EED4BA",
        "accent-sand-track": "#D9C8AA",
        "outline-variant": "#cfc4c5",
        "surface-container-highest": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "status-overdue-bg": "#EDEDED",
        "status-safe-fg": "#646B63",
        "secondary-fixed-dim": "#d2c6a7",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#c6c6c6",
        "surface-tint": "#5e5e5e",
        "inverse-primary": "#c6c6c6",
        "on-tertiary-fixed": "#1b1b1b",
        "white": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "16px": "16px"
      },
      spacing: {
        "md": "12px",
        "xs": "4px",
        "sm": "8px",
        "lg": "24px",
        "base": "16px",
        "xl": "32px",
        "6": "24px"
      },
      fontFamily: {
        "h1": ["Plus Jakarta Sans"],
        "display-numeric": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "h2": ["Plus Jakarta Sans"],
        "h1-mobile": ["Plus Jakarta Sans"],
        "label-medium": ["Inter"],
        "metadata": ["Inter"]
      },
      fontSize: {
        "h1": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-numeric": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "h2": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "h1-mobile": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "label-medium": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "metadata": ["12px", { lineHeight: "16px", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
}
